// import { ReactNode } from "react";
// import TOC from "./TOC";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
const geistSans=Geist({
  variable:"--font-geist-sans",
  subsets:["latin"]
});
const geistMono=Geist_Mono({
  variable:"--font-geist-mono",
  subsets:["latin"]
})
export const metadata:Metadata={
  title:"create next App",
  description:"generated by create next App"
}
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
    // <table>
    //   <tbody>
    //     <tr>
    //       <td valign="top" width="100px">
    //         {/*<TOC />*/}
    //         hello
    //       </td>
    //       <td valign="top">{children}</td>
    //     </tr>
    //   </tbody>
    // </table>

  );
}